# This is a GitHub Actions workflow file for linting Python code using Tox and Flake8.
name: Lint

on:
  push:
    branches:
      - '**'  # run on every push to any branch
  pull_request:
    branches:
      - master  # run on pull requests targeting the master branch

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      # Step 3: Run Tox for Linting
      - name: Run Tox Lint
        run: tox -e flake8

      # Step 4: Commit and push changes if Black reformats files
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Apply linting fixes" || echo "No changes to commit"
          git push